### DISCUSSION TITLE
RTSP stream in Home Assistant

### DISCUSSION THREAD

**Discussion by CodeFatherG** [QuantumEntangledAndy/neolink#255] [Q&A]
Hi! End goal is to use mqtt for state and rtsp for live view.

I am having trouble streaming this.

[As per a previous discussion](https://github.com/QuantumEntangledAndy/neolink/discussions/241#discussioncomment-9324516), vlc seems to timeout during connection. I was trying to get this running in home assistant somehow and from research was [going to use the ffmpeg integration](https://www.home-assistant.io/integrations/camera.ffmpeg/).

When I execute `ffmpeg -i 'rtsp link'` in terminal the docker logs show the following,
```
neolink  | [2024-05-12T10:46:29Z INFO  neolink::rtsp::stream] front_door_camera: Enabling Client
neolink  | [2024-05-12T10:47:06Z ERROR neolink::rtsp::stream] r: Err(App source is closed)
neolink  | [2024-05-12T10:47:06Z ERROR neolink::rtsp::stream] Exiting send_to_appsrc
neolink  | [2024-05-12T10:47:06Z INFO  neolink::rtsp::stream] front_door_camera: Pausing Client
```

Is there a recommended HA integration or even ffmpeg configuration I am missing to get the stream to work?

Is #253 possibly related causing timeouts?

<details>

# Compose
```yaml
version: '3.8'
services:
  neolink:
    image: quantumentangledandy/neolink:latest
    command: ["/usr/local/bin/neolink", "mqtt-rtsp", "--config=/etc/neolink.toml"]
    container_name: neolink
    ports:
      - 8554:8554
    volumes:
      - $PWD/neolink.toml:/etc/neolink.toml
    restart: unless-stopped
    network_mode: host
```

# Config
```yaml
# Expose on all networks
bind = "0.0.0.0"

# Define RTSP user
[[users]]
name = "admin"
pass = ...

# Front Camera
[[cameras]]
name = "front_door_camera"
discovery = "local"     # Discover local
username = "admin"      # Camera user
password = ...
address = "..."       # Reserved ip of camera
uid = "..."        # Camera UID
stream = "Main"
idle_disconnect = true          # Disconnect on idle for battery
  [cameras.pause]
  on_motion = true # Should pause when no motion
  on_client = true # Should pause when no rtsp client
[cameras.mqtt]
  [cameras.mqtt.discovery]
  topic = "homeassistant"       # Enable Discovery with the following controls
  features = ["Floodlight", "Camera", "Motion", "Reboot", "Battery", "Siren"]

[mqtt]
broker_addr = "127.0.0.1"       # local broker
port = 1883
credentials = ...
```

</details>
