### ISSUE TITLE
non updating mqtt entity

### ISSUE THREAD

**Issue by jonahgcarpenter** [QuantumEntangledAndy/neolink#113]
**Describe the bug**
The MQTT camera entity is not updating 

**To Reproduce**
```toml
bind = "0.0.0.0"

[[cameras]]
name = "Garage"
username = "admin"
password = "*****"
address = "*****"
  [cameras.mqtt]
  server = "*****" # Address of the mqtt server
  port = 1883 # mqtt servers port
  credentials = ["*****", "*****"] # mqtt server login details
    [cameras.mqtt.discovery]
    topic = "homeassistant"
    features = ["floodlight", "motion", "camera"]
```

**Expected behavior**
I was hoping the camera entity would update enough to send a notification including the photo when motion was detected

**Versions**
NVR software: Home Assistant
Neolink software: 0.0.6
Reolink camera model and firmware: LUMUS v2.0.0.705_21052800
