### ISSUE TITLE
Camera stays connected

### ISSUE THREAD

**Issue by Adammantium** [QuantumEntangledAndy/neolink#163]
**Describe the bug**
Hello there, im currently using the latest build of `feature/push_mqtt`. My cameras still stay connected, am I missing something?
I know its experimental, but i was hoping i would be able to test it.

**To Reproduce**
Steps to reproduce the behavior. Example:
1. Create this configuration file: 
```
[[cameras]]
name = "reolink1"
username = "admin"
password = "***"
uid = "***"
stream = "Main"
idle_disconnect = true
[cameras.mqtt]
enable_motion = true
enable_preview = true
battery_update = 60000
preview_update = 2000
```
I also tried adding the pause function, had no effect.
```
[cameras.pause]
on_motion = true
on_client = true
timeout = 2.1
```
3. Launch Neolink: neolink mqtt --config ...
4. Check MQTT, the camera stays connected

**Expected behavior**
I would expect MQTT to disconnect the cameras as long as there is no motion detected.
I don't want the preview to update all the time, only when a motion is detected (+ maybe every few minutes) so i can grab that picture.
Maybe i just didn't understand the configuration properly. `preview_update` is only the refresh interval inside of MQTT, right? Its not trying to take a picture every 2 seconds, my "framerate" seems to be 1 picture every 10 seconds.

**Versions**
NVR software:
Neolink software: 8bdb8ef1bd33bd14acc9555c15154295bdc075a2 (CI #941)
Reolink camera model and firmware: Reolink Argus Eco (v3.0.0.1981_23040606)
OS: Linux Debian 12

Any help would be appreciated! Thank you.

**Comment by QuantumEntangledAndy** [comment]
So from what I can see from your config it seems fine. You can set the preview to anything you want it will ignore it when I comes to idle disconnect and only take a preview when connected.

Perhaps you can set the environmental variable `RUST_LOG` to `"neolink=debug"` and post the debug log here. That will tell us what's happening

**Comment by QuantumEntangledAndy** [comment]
Also is that your exact config copy pasted? It will silently ignore some issue like spelling mistakes so please copy paste it in. 

Also for example this would not work

```toml
[[cameras]]
name = "reolink1"
username = "admin"
password = "***"
uid = "***"
stream = "Main"
[cameras.mqtt]
enable_motion = true
enable_preview = true
battery_update = 60000
preview_update = 2000
idle_disconnect = true
```

Because `idle_disconnect` is not a member of the `cameras.mqtt` sub table.

**Comment by QuantumEntangledAndy** [comment]
Here's the config I use for my tests

```toml
[[cameras]]
  name = "Cammy01"
  username = "****"
  password = "****"
  address = "****:9000"
  uid = "****"
  stream = "both"
  idle = true
```

`idle` is an undocumented alias for `idle_disconnect`. (I like to keep the keywords in my config short for easy typing, but the official names are long to better describe what they do)

**Comment by Adammantium** [comment]
> Also is that your exact config copy pasted? It will silently ignore some issue like spelling mistakes so please copy paste it in.
> 
> Also for example this would not work
> 
> ```toml
> [[cameras]]
> name = "reolink1"
> username = "admin"
> password = "***"
> uid = "***"
> stream = "Main"
> [cameras.mqtt]
> enable_motion = true
> enable_preview = true
> battery_update = 60000
> preview_update = 2000
> idle_disconnect = true
> ```
> 
> Because `idle_disconnect` is not a member of the `cameras.mqtt` sub table.

Oh sorry, you are right, i did some testing at put it in cameras.mqtt for one camera and in the main part for the other one to test it.
This is my whole config file:

```toml
bind = "0.0.0.0"

[mqtt]
broker_addr = "127.0.0.1" # Address of the mqtt server
port = 1883 # mqtt servers port
credentials = ["***", "***"] # mqtt server login details

[[cameras]]
name = "reolink1"
username = "admin"
password = "***"
uid = "***"
stream = "Main"
idle_disconnect = true
[cameras.pause]
on_motion = true
on_client = true
timeout = 2.1
[cameras.mqtt]
enable_pings = false
enable_motion = true
enable_preview = true
battery_update = 60000
preview_update = 2000

[[cameras]]
name = "reolink2"
username = "admin"
password = "***"
uid = "***"
stream = "Main"
idle_disconnect = true
[cameras.mqtt]
enable_pings = false
enable_motion = true
enable_preview = true
battery_update = 60000
preview_update = 2000

[cameras.mqtt.discovery]
topic = "homeassistant"
features = ["camera", "ir", "motion", "battery"]
```

**Comment by Adammantium** [comment]
I also just send you my log file via mail, it looks like its holding a lot of private information.
Do you need the file /root/.config/./neolink_token.toml as well? Seems like there is only one key in there:
```toml
fcm_token = "***"

[gcm]
android_id = "***"
security_token = "***"

[keys]
public_key = "***"
private_key = "***"
auth_secret = "***"
```
Maybe its an issue because im using 2 cameras?
