### ISSUE TITLE
Not connecting to the mqtt server

### ISSUE THREAD

**Issue by Roei639** [QuantumEntangledAndy/neolink#208]
Hello, 
neolink does not connect to the mqtt server, there is no error in the blog.

docker-compose:
```
  neolink:
    image: quantumentangledandy/neolink:latest
    container_name: neolink
    ports:
      - 8556:8554
    volumes:
      - /docker/docker-mounts/neolink/neolink.toml:/etc/neolink.toml
    restart: unless-stopped
```

configuration neolink.toml:
```
bind = "0.0.0.0"
[mqtt]
broker_addr = "10.100.102.253" # Address of the mqtt server
port = 1883 # mqtt servers port
credentials = ["myuser", "mypassword"] # mqtt server login details

[[cameras]]
name = "namecamera"
username = "xxxxx"
password = "xxxxx"
uid = "xxxxxxx"
```
