### ISSUE TITLE
Delayed MQTT Motion

### ISSUE THREAD

**Issue by ThePapaG** [QuantumEntangledAndy/neolink#257]
# Describe the bug
The motion being communicated over MQTT is delayed. The aim is to use the motion to turn on the front lights which are not battery powered therefore saving on battery but the time to detect motion in MQTT is so long that it is unusable.

As soon as I walk into frame the camera lights up and starts recording but the motion automation in home assistant takes up to a minute to trigger and turn on the lights.

# To Reproduce
Steps to reproduce the behavior. Example:
1. Create this configuration file:
```yaml
bind = "0.0.0.0"

# Define RTSP user
[[users]]
name = "admin"
pass = ...

# Front Camera
[[cameras]]
name = "front_door_camera"
discovery = "local"     # Discover local
username = "admin"      # Camera user
password = ...    # Camera on board pw
address = ...       # Reserved ip of camera
uid = ...        # Camera UID
stream = "Main"
idle_disconnect = true          # Disconnect on idle for battery
  [cameras.pause]
  on_motion = true # Should pause when no motion
  on_client = true # Should pause when no rtsp client
[cameras.mqtt]
  [cameras.mqtt.discovery]
  topic = "homeassistant"       # Enable Discovery with the following controls
  features = ["Floodlight", "Camera", "Motion", "Reboot", "Battery", "Siren"]

[mqtt]
broker_addr = "127.0.0.1"       # local broker
port = 1883
credentials = ...
```
2. Launch Neolink:
```yaml
version: '3.8'
services:
  neolink:
    image: quantumentangledandy/neolink:latest
    command: ["/usr/local/bin/neolink", "mqtt-rtsp", "--config=/etc/neolink.toml"]
    container_name: neolink
    ports:
      - 8554:8554
    volumes:
      - $PWD/neolink.toml:/etc/neolink.toml
    restart: unless-stopped
    network_mode: host
```
3. `docker compose up`
4. monitor motion entity in home assistant

# Expected behavior
The motion be communicated to MQTT not long after the camera has started recording (indicating that it has detected motion).

# Logs

<details>

<summary>Logs</summary

The log contains two motion events confirmed in mqtt both with varying results. The first motion was close to being acceptable delay. The second was as with every other test I have ever ran, up to a minute.

Logs are too long, sorry but I didn't want to cut them up in case of context

[neolink_motion_logs.txt](https://github.com/QuantumEntangledAndy/neolink/files/15307339/neolink_motion_logs.txt)

</details>

# Versions
Neolink software: 82524a12b2a218b8d088029e19158ed9f44de9b8 release
Reolink camera model and firmware: v3.0.0.2773_23100910
