### ISSUE TITLE
Can't integrate with Home Assistant. 

### ISSUE THREAD

**Issue by Centretard** [QuantumEntangledAndy/neolink#268]
When I try and install the neolink custom repository in HASS I get the following error -

'Integration QuantumEntangledAndy/neolink> Repository structure for v0.6.2 is not compliant'

I'm not sure if I'm doing this correctly, I'm new to this. If someone knows if I'm going wrong and could point me in the right direction, I would appreciate it. 

Thanks

Cent

**Comment by s3than** [comment]
I can answer this for you..

Basically it's not a HASS integration.. 

You need to do something like the following

MQTT Config
Camera -> Neolink Service (docker) -> MQTT (either HASS or separate) -> HASS MQTT Device

RTSP Config
Camera -> Neolink Service (docker) -> HASS RTSP Device

I've got a battery Reolink and have configured only the top one as the battery usage on the rtsp is pretty high.. 
Most of the MQTT auto discovery worked for me however I configured the following button

```
        mqtt:
          button:
            - name: "Wake Camera"
              unique_id: external_camera_wake_btn
              command_topic: "neolink/external/control/wakeup"
              payload_press: "1"
              device:
                connections:
                  - - camera_addr
                    - 192.168.80.44
                  - - camera_uid
                    - 95270007989PEHKE
                identifiers:
                  - neolink_external
              qos: 0
              retain: false
```

Which I have on a automation to trigger every 30 minutes or so... this get's battery and stats etc..

It also enables me to have a dashboard where I can press the button and view the mqtt preview camera.. which is a couple seconds delayed and every 2 secs.. so not live but enough for me to view.. 

I'll be setting the camera up to FTP motion video itself that way power usage should be very low.. 

Hope this helps
