### ISSUE TITLE
Neolink Feed "Brighter"/Overexposed Compared To Reolink App Or Webpage

### ISSUE THREAD

**Issue by royaltongue** [QuantumEntangledAndy/neolink#358]
**Describe the bug**
When viewing the feed of my camera from Neolink in Frigate, the image is brighter/whiter/overexposed than it's supposed to be

**To Reproduce**
Steps to reproduce the behavior. Example:
1. Create this configuration file:
```
bind = "0.0.0.0"
discovery = "local"

[[cameras]]
name = "doorbell"
username = "admin"
password = "[redacted]"
uid = "[redacted]"
address = "192.168.3.8"
```
2. Launch Neolink:
3. Frigate configuration:
```
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://neolink:8554/doorbell/main
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    record:
      enabled: false
    detect:
      enabled: false
      width: 1920
      height: 1080
      fps: 20
```
4. View camera feed from inside Frigate

**Expected behavior**
Camera feed should be the same

# Pictures:
From Reolink directly:
![Image](https://github.com/user-attachments/assets/c2696b45-fa75-4731-8529-2535b7393263)

From Frigate:
![Image](https://github.com/user-attachments/assets/665932d6-1d49-420e-911e-8773979810a1)

**Versions**
NVR software: Frigate 0.15.0-6cb5cfb
Neolink software: 6e05e7844b5b50f89787d30bffcbbd3471bfcfde in Docker
Reolink camera model and firmware: Reolink WiFi Doorbell v3.0.0.4662_2503122270
