### ISSUE TITLE
Camera set to the wrong time, off by -2 hours

### ISSUE THREAD

**Issue by T-Lancer** [QuantumEntangledAndy/neolink#361]
**Describe the bug**
my B400 Camera appears to be running with the wrong time.  neolink sets the time to the wrong value.  the time is off by -2hours

Container logs show time also incorrectly.

Container Console however shows the correct time when running "date"

**To Reproduce**
configure neolink as normal.
allow neolink to connect to the camera
let it set the time

**Expected behavior**
neolink should set the time correctly.

**Versions**
NVR software: frigate in Docker
Neolink software: 6.2
Reolink camera model and firmware: B400 v2.0.0.16_20041550

Docker compose:

```
version: '3.8'
services:
  neolink:
    image: quantumentangledandy/neolink # If a specific version should be targetted, target it here with `:vx.x.x`
    command: ["/usr/local/bin/neolink", "rtsp", "--config=/etc/neolink.toml"]  # The NEO_LINK_MODE can be set by modifying this command
    container_name: neolink
    ports:
      - 8556:8556
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /home/docker_data/neolink/neolink.toml:/etc/neolink.toml
    restart: unless-stopped
    #network_mode: host # As above, if the network host is required, uncomment this.
    deploy:
      resources:
        limits:
          #cpus: '0.001'
          memory: 500M  #memory leak mitigation, crashes and restarts when limit reached. 
    memswap_limit: 500M  #memory leak mitigation, crashes and restarts when limit reached. 
```

neolink.toml:
```
bind = "0.0.0.0"

# Default port is 8554 but you can change it by uncommenting the following
bind_port = 8556

[[cameras]]
name = "cellar"
username = "homeassistant"
password = "REDACTED"
address = "REDACTED"
format = "H264"
push_notifications = false
update_time = true


```
