### ISSUE TITLE
Not working with go2rtc

### ISSUE THREAD

**Issue by moskovskiy82** [QuantumEntangledAndy/neolink#77]
I feel this is somehow related to internal workings of neolink, but i might be wrong

https://github.com/blakeblackshear/frigate/discussions/6295

**Comment by QuantumEntangledAndy** [comment]
Sorry I'm having trouble understanding what you are doing in that other thread. Not familiar with the workings of go2rtc or frigate.

Where is neolink in this setup and how are you connecting to it and what error do you get?

**Comment by moskovskiy82** [comment]
Reolink B800 > Your fork of Neolink. (Had to change the port to 8551  as go2rtc uses 8554 as well) > go2rtc > frigate

The problem is that the go2rtc part is not working. If i skip it out - it works. Go2rtc is like a video proxy allowing to convert for example the H265 stream to H264. Not good at video on linux - but can it be some kind of a conflict between Neolink and go2rtc? Although both run in docker containers.

**Comment by moskovskiy82** [comment]
Have also posted on go2rtc site. It's just strange that non Neolink cameras work without a hitch. So the problem is somewhere in between and i would appreciate if you could help with you knowledge

https://github.com/AlexxIT/go2rtc/issues/392

**Comment by QuantumEntangledAndy** [comment]
Perhaps you can give me some more clear error messages/logs. It's hard to trace an issue without them.

Your using docker so i hope your aware of the extra work required to get a connection. Each container has its own ip and you need to know the IP address of the container for a connection. (If your using compose you can use the link parameter to give them names instead of IPs)

**Comment by QuantumEntangledAndy** [comment]
For neolink the two variables that control logging are

RUST_LOG="debug"

And

GST_DEBUG=3

**Comment by moskovskiy82** [comment]
> Your using docker so i hope your aware of the extra work required to get a connection. Each container has its own ip and you need to know the IP address of the container for a connection. (If your using compose you can use the link parameter to give them names instead of IPs)

Yes. So to make things work i just expose the necessary ports. That is why had to change the Neolink port as it was the same as go2rtc (8554) which is a weird similarity to me and that is why i opened an issue here as well as you understand the internal workings of Neolink and have the knowledge.  Will do some debug logging as currently no errors are logged neither in go2rtc or Neolink side which is just strange

```
version: "2.7"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "2048mb
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime:ro
      - /i/frigate/config.yml:/config/config.yml
      - /i/frigate/media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 4000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
      - "8554:8554"
    environment:
      - LIBVA_DRIVER_NAME=radeonsi
      - PGID=1001

  neolink:
    image: quantumentangledandy/neolink
    container_name: neolink
    ports:
      - 8551:8551
    volumes:
      - /i/frigate/neolink.toml:/etc/neolink.toml
    restart: unless-stopped

```

**Comment by QuantumEntangledAndy** [comment]
8554 is the standard rtsp port. So anything the provides rtsp will probably have it for the default.

Could you provide the following:

1. The neolink config 
2. The config for frigate that shows the rtsp url it is connecting to

**Comment by QuantumEntangledAndy** [comment]
Ok so I've added some things to improve the connection on VLC and frigate I hope it helps you. Could you test the latest build?

Also do you actually need go2rtc to convert the video? If you have a specific reason I might try and work up some conversion into neolink itself

**Comment by QuantumEntangledAndy** [comment]
Just thought I'd share the test docker and frigate setup I use

docker-compose.yml
```yml
version: "3.9"
services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    links:
      - neolink
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate.yml:/config/config.yml
      - ./storage:/media/frigate
      - ./db:/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
  neolink:
    image: quantumentangledandy/neolink:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./neolink.toml:/etc/neolink.toml
    environment:
      RUST_LOG: "neolink=debug"
```

neolink.toml
```toml
bind = "0.0.0.0"

[[cameras]]
name = "ANAME"
username = "MYUSER"
password = "MYPASS"
address = "MYIP:9000"
uid = "MYUID"
stream = "subStream"
```

frigate.yml
```yml
database:
    path: /db/frigate.db

mqtt:
    enabled: false

cameras:
    ANAME:
      ffmpeg:
        inputs:
          - path: rtsp://neolink:8554/ANAME/subStream
      detect:
        enabled: False
        width: 1280 # <---- update for your camera's resolution
        height: 720
```
