### ISSUE TITLE
Errors when streaming from Argus Eco

### ISSUE THREAD

**Issue by mattlcbesc** [QuantumEntangledAndy/neolink#78]
**Describe the bug**
Stream works in VLC on another PC on the LAN.  However, it will not work with Frigate and also get errors using FFPROBE.   FFPROBE confirms GSTREAMER is loading and producing data, but it is not ingesting any video stream it would appear.  

**To Reproduce**
Steps to reproduce the behavior.
CONFIG:                               
bind = "192.168.27.114"

[[cameras]]
name = "homesite"
username = "admin"
password = "10champs11"
address = "192.168.27.105"
uid = "95270000WZMJ0ZRY"
format = "h264"
  [cameras.pause]
  on_motion = true # Should pause when no motion
  on_client = true # Should pause when no rtsp client
  timeout = 2.1 # How long to wait after motion stops before pausing

**Expected behavior**
Stream should be readable from Frigate and not produce errors from FFPROBE. 

**Versions**
NVR software:    Frigate 0.12.0
Neolink software:     0.5.8
Reolink camera model and firmware:   Argus Eco  1202_491_352_19

NEOLINK Debug:  https://pastebin.com/zy2iSBtC

FFPROBE Output:   https://pastebin.com/AzS1pGFC

**Comment by mattlcbesc** [comment]
- path: rtsp://192.168.27.114:8554/homesite # <----- The stream you want to use for detection
 
 ^^  Path used in Frigate for rtsp stream

**Comment by QuantumEntangledAndy** [comment]
Might be best to test without pause on so we can eliminate the issue as comming from the start up time.

We are currently testing a rework of the stream data in #68 that might help with frigate. But the testers there are getting issue I can't replicate. Perhaps you can give it a try especially if your on another os

**Comment by mattlcbesc** [comment]
No change in what I'm seeing from Frigate.  Here's an updated log from neolink:  https://pastebin.com/KcjpWqhQ

ffprobe from the frigate system acts like it's not receiving any data now.

**Comment by QuantumEntangledAndy** [comment]
From what I can see with that. It's just that the rtsp stream in frigate is trying to run faster than the stream is pulling data. I'll see if I can smooth this out when I get a moment to work on the code

How are you viewing the stream in frigate? I've just gotten a setup for testing purposes but Ive never used it before. Are your  looking at it from the webui or do I need to test the view on it's own rtsp feed?

**Comment by mattlcbesc** [comment]
I normally view from the standard webui.  I did comment out the pause lines as well.   Below is my config for the rtsp feed from neolink in frigate.  

```
  homesite: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://192.168.27.114:8554/homesite/subStream # <----- The stream you want to use for detection
          input_args: 
            - preset-rtsp-restream
          roles:
            - detect
            - record

```

**Comment by QuantumEntangledAndy** [comment]
Can you check again with the latest build? I've added some code to buffer and apply time stamps better for VLC and frigate that seems to be working for me

**Comment by mattlcbesc** [comment]
Also, i had to use go2rtc in Frigate to get the video feed working.  Were you able to ingest the feed in Frigate directly from Neolink?  Or did you have to go through go2rtc?  Mind sharing your frigate camera settings if you didnt use go2rtc?   Thanks

**Comment by QuantumEntangledAndy** [comment]
Buffer exhausted seems to happen when the video is too large to be handled quickly enough to be live. Try reducing the bit rate etc using the official app first.

I just used the default config in frigate. No options other than the address really.

**Comment by QuantumEntangledAndy** [comment]
Just thought I'd share the test docker and frigate setup I use

docker-compose.yml
```yml
version: "3.9"
services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    links:
      - neolink
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate.yml:/config/config.yml
      - ./storage:/media/frigate
      - ./db:/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
  neolink:
    image: quantumentangledandy/neolink:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./neolink.toml:/etc/neolink.toml
    environment:
      RUST_LOG: "neolink=debug"
```

neolink.toml
```toml
bind = "0.0.0.0"

[[cameras]]
name = "ANAME"
username = "MYUSER"
password = "MYPASS"
address = "MYIP:9000"
uid = "MYUID"
stream = "subStream"
```

frigate.yml
```yml
database:
    path: /db/frigate.db

mqtt:
    enabled: false

cameras:
    ANAME:
      ffmpeg:
        inputs:
          - path: rtsp://neolink:8554/ANAME/subStream
      detect:
        enabled: False
        width: 1280 # <---- update for your camera's resolution
        height: 720
```
