### ISSUE TITLE
Frigate - Streaming with audio stops

### ISSUE THREAD

**Issue by Veuchez** [QuantumEntangledAndy/neolink#91]
Today I managed to configure Frigate with the audio stream. 
Unfortunately I notice that when the audio "skips", the stream stops. 
I attach the log. 
[log2.txt](https://github.com/QuantumEntangledAndy/neolink/files/11530669/log2.txt)
The cameras Reolink Argus 3 PRO are at 1536kbps
What are all those "Pausing" that I see in the log?
Here is my Frigate configuration:
```
mqtt:
  enabled: False  

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-copy

cameras:
  c5:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.3.170:8554/c5 # 
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: False 
      width: 2560
      height: 1440

go2rtc:
  streams:
    c5:
      - "ffmpeg:rtsp://192.168.0.150:8554/c5#audio=aac"
      - rtsp://192.168.0.150:8554/c5
```
